name: 'fm-backend-pre-check'
description: 'Custom FM Backend actions'
inputs:
  npm_token:
     description: "npm access token"
     required: true
  ci_ssh_token:
     description: "Optional ssh key for fm-ci user"
     required: false
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/validate-tests.sh
      shell: bash
    - run: echo '//registry.npmjs.org/:_authToken=${{ inputs.npm_token  }}' > ~/.npmrc
      shell: bash
    - run: mkdir ~/.ssh && echo '${{ inputs.ci_ssh_token  }}' > ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa
      shell: bash
      if: ${{ inputs.ci_ssh_token  }}
