name: 'fm-backend-pre-check'
description: 'Custom FM Backend actions'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/validate-tests.sh
      shell: bash
    - run: echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN  }}' > ${{ github.workspace }}/.npmrc
      shell: bash
