name: 'fm-backend-pre-check'
description: 'Custom FM Backend actions'
inputs:
  npm_token:
     description: "npm access token"
     required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/validate-tests.sh
      shell: bash
    - run: echo '//registry.npmjs.org/:_authToken=${{ inputs.npm_token  }}' > ~/.npmrc
      shell: bash
