name: Codecov master

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: flitsmeister/backend-actions-check@main
      with:
        npm_token: ${{ secrets.NPM_TOKEN }}
    - uses: actions/setup-node@v3
      with:
        node-version: '14'

    - run: npm install
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: npm run codecov
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage/coverage-final.json
        fail_ci_if_error: true
