name: Codecov master

on:
  workflow_call:
    inputs:
      aptPackages:
        required: false
        type: string
    secrets:
      NPM_TOKEN:
        required: true
      CODECOV_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: flitsmeister/backend-github-actions@master
      with:
        npm_token: ${{ secrets.NPM_TOKEN }}
    - uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install packages
      run: sudo apt-get update; sudo apt-get install -y ${{ inputs.aptPackages }}
      if: ${{ inputs.aptPackages }}

    - run: npm install

    - name: Install npm packages
      run: npm install -g nyc

    - run: nyc --reporter=json npm test -- --timeout 10000

    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage/coverage-final.json
        fail_ci_if_error: true
