name: Codecov

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: npm run codecov
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage/coverage-final.json
        fail_ci_if_error: true
