name: Integrationtest

on:
  workflow_call:
    inputs:
      redis:
        required: false
        type: boolean
      mongo:
        required: false
        type: boolean
      mysql:
        required: false
        type: boolean
      postgres:
        required: false
        type: boolean
      postgres-name:
        required: false
        type: string

jobs:
  integrationtest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Remember package.json hash
      id: vars
      run: echo ::set-output name=package_json_hash::$(cat package.json | openssl dgst -sha256 -binary | xxd -p  -c 256)

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-cache-node-modules-${{steps.vars.outputs.package_json_hash}}

    - name: MongoDB server
      if: ${{ inputs.mongo }}
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: '4.2'

    - name: MongoDB client
      if: ${{ inputs.mongo }}
      run: |
        wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
        echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
        sudo apt-get update
        sudo apt-get install -y mongodb-org-shell

    - name: Postgres
      if: ${{ inputs.postgres }}
      uses: ireznik/postgis-action@v12
      with:
        postgresql version: '12-master'
        postgresql db: ${{ inputs.postgres-name }}
        postgresql user: ${{ inputs.postgres-name }}
        postgresql password: ${{ inputs.postgres-name }}

    - name: Sleep for 10 seconds for startup of postgres
      if: ${{ inputs.postgres }}
      run: sleep 10s
      shell: bash

    - name: Redis
      if: ${{ inputs.redis }}
      run: sudo apt-get install -y redis-server

    - name: Mysql
      if: ${{ inputs.mysql }}
      uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: '5.7'

    - run: npm run | grep prepare > /dev/null && npm run-script prepare
    - run: npm run integrationtest
