name: Setup project

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: flitsmeister/backend-actions-check@main
      with:
        npm_token: ${{ secrets.NPM_TOKEN }}
    - uses: actions/setup-node@v3
      with:
        node-version: '14'

    - run: npm install
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
