name: Setup project

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
      CI_SSH_KEY:
        required: false
    inputs:
      skipValidations:
        required: false
        type: boolean

jobs:
  setup:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
    - uses: actions/checkout@v3
    - uses: flitsmeister/backend-github-actions@master
      with:
        npm_token: ${{ secrets.NPM_TOKEN }}
        ci_ssh_key: ${{ secrets.CI_SSH_KEY }}
      if: ${{ ! inputs.skipValidations }}

    - uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Remember package.json hash
      id: vars
      run: echo "package_json_hash=$(cat package.json | openssl dgst -sha256 -binary | xxd -p -c 256)" >> $GITHUB_OUTPUT

    - run: npm install

    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-cache-node-18-modules-${{steps.vars.outputs.package_json_hash}}
