name: Unit tests

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'

    - run: export PACKAGE_JSON_HASH=$(cat package.json | openssl dgst -sha256)
    - run: echo "package.json hash = $PACKAGE_JSON_HASH" && cat package.json

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-cache-node-modules-${{ env.PACKAGE_JSON_HASH }}

    - run: npm test
    - run: ./node_modules/eslint/bin/eslint.js --quiet -c node_modules/@flitsmeister/eslint/.eslintrc --ignore-pattern node_modules --ignore-pattern public .
    - run: npm run codecov
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage/coverage-final.json
        fail_ci_if_error: false
