name: Unit tests

on:
  workflow_call:
    inputs:
      aptPackages:
        required: false
        type: string
      skipFlakyCheck:
        required: false
        type: boolean
    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Remember package.json hash
      id: vars
      run: echo "package_json_hash=$(cat package.json | openssl dgst -sha256 -binary | xxd -p -c 256)" >> $GITHUB_OUTPUT

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-cache-node-18-modules-${{steps.vars.outputs.package_json_hash}}

    - name: Install apt packages
      run: sudo apt-get update; sudo apt-get install -y ${{ inputs.aptPackages }}
      if: ${{ inputs.aptPackages }}

    - name: Run setup script if available
      run: npm run | grep setup > /dev/null && npm run-script setup || true
    - name: Run unit tests
      run: npm test
    - name: Run unit tests multiple times to find flaky tests
      run: for i in `seq 5`; do npm test; done
      if: ${{ ! inputs.skipFlakyCheck }}
    - name: Linting
      run: ./node_modules/eslint/bin/eslint.js --quiet -c node_modules/@flitsmeister/eslint/.eslintrc --ignore-pattern node_modules --ignore-pattern helpers --ignore-pattern public --ignore-pattern web --ignore-pattern build --ignore-pattern src .
    - name: Install npm packages
      run: npm install -g nyc
    - name: Code coverage
      run: nyc --reporter=json npm test -- --timeout 5000 -v
    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage/coverage-final.json
        fail_ci_if_error: false
